# Generated by Django 4.0.2 on 2022-02-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=100)),
                ('game_origin', models.CharField(blank=True, max_length=100, null=True)),
                ('ref_id', models.CharField(max_length=20, null=True)),
                ('ref_link', models.CharField(max_length=100, null=True)),
                ('icon_link', models.CharField(max_length=100, null=True)),
                ('sprite', models.CharField(max_length=100, null=True)),
                ('portrait', models.CharField(max_length=100, null=True)),
                ('attack', models.CharField(max_length=100, null=True)),
                ('special', models.CharField(max_length=100, null=True)),
                ('damaged', models.CharField(max_length=100, null=True)),
                ('voice_1', models.CharField(max_length=100, null=True)),
                ('voice_2', models.CharField(max_length=100, null=True)),
                ('line_1', models.TextField(null=True)),
                ('line_2', models.TextField(null=True)),
                ('summary', models.TextField(null=True)),
                ('realm', models.CharField(max_length=60)),
                ('realm_index', models.IntegerField()),
                ('release_date', models.DateTimeField()),
                ('index', models.IntegerField()),
            ],
        ),
    ]
