# Generated by Django 2.2.24 on 2022-02-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=100)),
                ('icon_link', models.CharField(max_length=100)),
                ('miniImageLink', models.CharField(max_length=100)),
                ('ImageLink', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/')),
                ('voice_1', models.CharField(max_length=100)),
                ('voice_2', models.CharField(max_length=100)),
                ('summary', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
