# Generated by Django 4.0.2 on 2022-02-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_character_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='release_date',
            field=models.DateTimeField(),
        ),
    ]
