# Generated by Django 2.2.24 on 2022-02-13 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_character'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='ImageLink',
        ),
        migrations.RemoveField(
            model_name='character',
            name='icon_link',
        ),
        migrations.RemoveField(
            model_name='character',
            name='image',
        ),
        migrations.RemoveField(
            model_name='character',
            name='miniImageLink',
        ),
        migrations.RemoveField(
            model_name='character',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='character',
            name='voice_1',
        ),
        migrations.RemoveField(
            model_name='character',
            name='voice_2',
        ),
    ]
