# Generated by Django 2.2.24 on 2022-02-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220213_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='icon_link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='imageLink',
            field=models.CharField(max_length=260, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='miniImageLink',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='voice_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='voice_2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
