# Generated by Django 2.2.24 on 2022-02-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220213_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='ref_link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
